version: '3'
services:
  nginx1:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./laravel1:/var/www/html
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    links:
      - php1
  nginx2:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./laravel2:/var/www/html
      - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    links:
      - php2
  php1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel1:/var/www/html
    depends_on:
      - mysql
  php2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel2:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - 3306:3306  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8082:80
  something:
    build:
      context: ./something
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8090:80'
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock